-- autocmds.lua — load-bearing autocommands.
-- LazyVim covers split-resize, trim-whitespace (via conform), and most
-- ergonomic defaults.
--
-- Filetype detection for yaml.github lives in options.lua, not here:
-- LazyVim loads config.autocmds on the VeryLazy event, which fires
-- AFTER cmdline-opened buffers have had their filetype resolved. A
-- vim.filetype.add placed here would only apply to files opened via
-- :edit during a running session, not to `nvim .github/workflows/ci.yml`.
