# kitty/dracula-pro.conf — Dracula Pro palette for kitty
# Palette values from docs/plans/2026-04-12-shell-modernisation-design.md § 3.9
# (Not redistributed from the paid Dracula Pro package — reconstructed from the
# public palette spec.)

foreground            #F8F8F2
background            #282A36
selection_foreground  #F8F8F2
selection_background  #44475A

url_color             #8BE9FD
cursor                #F8F8F2
cursor_text_color     #282A36

active_tab_foreground   #282A36
active_tab_background   #BD93F9
inactive_tab_foreground #F8F8F2
inactive_tab_background #44475A

# ANSI 16-color palette
color0  #21222C
color1  #FF5555
color2  #50FA7B
color3  #F1FA8C
color4  #BD93F9
color5  #FF79C6
color6  #8BE9FD
color7  #F8F8F2
color8  #6272A4
color9  #FF6E6E
color10 #69FF94
color11 #FFFFA5
color12 #D6ACFF
color13 #FF92DF
color14 #A4FFFF
color15 #FFFFFF
