# config.yml — lazygit configuration
# See docs/design/git.md for the specification.

gui:
  theme:
    activeBorderColor:
      - '#9580FF'
      - bold
    inactiveBorderColor:
      - '#7970A9'
    optionsTextColor:
      - '#F8F8F2'
    selectedLineBgColor:
      - '#454158'
    selectedRangeBgColor:
      - '#454158'
    cherryPickedCommitBgColor:
      - '#454158'
    cherryPickedCommitFgColor:
      - '#9580FF'
    unstagedChangesColor:
      - '#FF9580'
    defaultFgColor:
      - '#F8F8F2'
    searchingActiveBorderColor:
      - '#FFFF80'
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  showFileTree: true
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --paging=never --syntax-theme='Dracula Pro'
  commit:
    signOff: false
  fetching:
    interval: 60

keybinding:
  universal:
    quit:            q
    return:          "<esc>"
    scrollUpMain:    k
    scrollDownMain:  j
    prevItem:        k
    nextItem:        j
    scrollLeft:      h
    scrollRight:     l
    nextTab:         "]"
    prevTab:         "["
    openRecentRepos: "<c-r>"
